### ISSUE TITLE
Installation error Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by tusharvb19** [macchina-io/macchina.io#60]
ubuntu@ip-:\~/macchina.io$ export LD_LIBRARY_PATH=`pwd`/platform/lib/Linux/x86_64
ubuntu@ip-:\~/macchina.io$ cd server
ubuntu@ip-:\~/macchina.io/server$ bin/Linux/x86_64/macchina
-bash: bin/Linux/x86_64/macchina: No such file or directory

**Comment by tusharvb19** [comment]
*the line marker is due to typo!

**Comment by tusharvb19** [comment]
Same issue while installing on NanoPi NEO with DietPi which is based on jessy!

**Comment by obiltschnig** [comment]
You'll need to provide more information. Did it actually build successfully in the first place?

**Comment by tusharvb19** [comment]
Nope...I tried on a ubuntu 6.04 LTS on AWS EC2 but the same error!
Can someone try on the cloud or on raspberry pi?

**Comment by Bobo-Anton** [comment]
I may have the same problem. I'm on ubuntu 16.10 and the build wasn't successfully - error with libv8.so not being there. I see that this problem was already reported in "Building for Raspberry Pi 2 (armv7) on Ubuntu 17.04 fails" a few months ago, but not sure if a solution for this was integrated. The prerequisites for compiling the project were met in my case. Any suggestion on how i can solve this problem is much appreciated!

** Compiling src/Parameter.cpp (release, shared)
Segmentation fault (core dumped)
tools/gyp/v8_snapshot.target.x64.release.mk:13: recipe for target '/home/bobo/macchina.io/platform/JS/V8/v8-3.28.4/out/x64.release/obj.target/v8_snapshot/geni/snapshot.cc' failed
make[4]: *** [/home/bobo/macchina.io/platform/JS/V8/v8-3.28.4/out/x64.release/obj.target/v8_snapshot/geni/snapshot.cc] Error 139
Makefile:280: recipe for target 'x64.release' failed
make[3]: *** [x64.release] Error 2
cp: cannot stat 'v8-3.28.4/out/x64.release/lib.target/libv8.so': No such file or directory
Makefile:102: recipe for target 'v8install' failed
make[2]: *** [v8install] Error 1
Makefile:271: recipe for target 'JS/V8-libexec' failed
make[1]: *** [JS/V8-libexec] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by obiltschnig** [comment]
Try compiling with:
```
make -s -j8 DEFAULT_TARGET=shared_release V8_NOSNAPSHOT=1
```
(disabling the V8 snapshot feature causing the issue)

**Comment by Bobo-Anton** [comment]
Thanks for the solution. Works like a charm.
